Repository Trustless-Work/dApp-Trustless-Work, pull requests merged in 2024-12, with the labels that each got.

#39 Feat/create escrow
  package-lock.json
  src/app/escrow/create-escrow/page.tsx
  src/components/ui/card.tsx
  src/components/ui/steps.tsx
  src/services/deploy/createEscrow.ts
Labels: enhancement

#63 PR-feat/breadcrumb in header
  src/components/header/Header.tsx
Labels: enhancement, external-contributors, Maintainer - Caleb Loría

#76 refactor(escrow): modularize escrow creation components and add stepp…
  src/app/dashboard/escrow/create-escrow/page.tsx
  src/components/modules/escrow/CreateEscrow.tsx
  src/components/modules/escrow/EscrowSteps/EscrowStepper.tsx
  src/components/modules/escrow/EscrowSteps/StepButton.tsx
  src/components/modules/escrow/EscrowSteps/StepContent.tsx
  src/components/modules/escrow/InitEscrow.tsx
  src/components/modules/escrow/InitializeEscrowForm.tsx
  src/components/modules/escrow/hooks/initialize-escrow.hook.ts
  src/store/EscrowStepStore/store.ts
  src/store/escrowFormStore/store.ts
Labels: enhancement, external-contributors, Maintainer - Joel Vargas, ODHack11
