Repository Trustless-Work/dApp-Trustless-Work, pull requests merged in 2025-07, with the labels that each got.

#201 Feat/history page escrows
  public/locales/en/common.json
  public/locales/es/common.json
  src/app/dashboard/history/page.tsx
  src/app/globals.css
  src/components/layout/sidebar/constants/sidebar-items.constant.ts
  src/components/modules/history/@types/history.entity.ts
  src/components/modules/history/constants/table-columns.constant.ts
  src/components/modules/history/hooks/useHistory.hook.ts
  src/components/modules/history/hooks/useHistoryQuery.ts
  src/components/modules/history/pages/History.tsx
  src/components/modules/history/tables/HistoryTable.tsx
Labels: enhancement, external-contributors, onlydust-wave

#203 Feat/implement chat logic
  src/@types/conversation.entity.ts
  src/components/modules/chat/constants/mock-conversations.constant.ts
  src/components/modules/chat/hooks/chat.hook.ts
  src/components/modules/chat/hooks/useFileAttachment.hook.ts
  src/components/modules/chat/server/chat.firebase.ts
  src/components/modules/chat/ui/components/ChatHeader.tsx
  src/components/modules/chat/ui/components/ChatInput.tsx
  src/components/modules/chat/ui/components/ChatInterface.tsx
  src/components/modules/chat/ui/components/ChatMessage.tsx
  src/components/modules/chat/ui/pages/Chats.tsx
Labels: enhancement, external-contributors, Maintainer - Joel Vargas, onlydust-wave

#204 Feat/auth UI login page
  src/app/login/page.tsx
  src/components/layout/header/HeaderWithoutAuth.tsx
  src/components/modules/login/ui/pages/Login.tsx
  yarn.lock
Labels: enhancement, external-contributors, onlydust-wave

#209 Feat/implement user endpoints
  package-lock.json
  package.json
  src/@types/issue.entity.ts
  src/@types/user.entity.ts
  src/app/dashboard/chats/page.tsx
  src/app/dashboard/report-issue/page.tsx
  src/app/report-issue/page.tsx
  src/components/layout/header/HeaderWithoutAuth.tsx
  src/components/layout/header/hooks/header-without-auth.hook.ts
  src/components/layout/sidebar/constants/sidebar-items.constant.ts
  src/components/modules/auth/login/ui/pages/Login.tsx
  src/components/modules/auth/server/authentication.firebase.ts
  src/components/modules/auth/services/auth.service.ts
  src/components/modules/chat/hooks/chat.hook.ts
  src/components/modules/chat/hooks/useFileAttachment.hook.ts
  src/components/modules/chat/hooks/useUnreadFilter.hook.ts
  src/components/modules/chat/server/chat.firebase.ts
  src/components/modules/chat/ui/ChatButton.tsx
  src/components/modules/chat/ui/DateSeparator.tsx
  src/components/modules/chat/ui/FloatingChat.tsx
  src/components/modules/chat/ui/MessageBubble.tsx
  src/components/modules/chat/ui/MessageInput.tsx
  src/components/modules/chat/ui/MessageList.tsx
  src/components/modules/chat/ui/components/ChatHeader.tsx
  src/components/modules/chat/ui/components/ChatInput.tsx
  src/components/modules/chat/ui/components/ChatInterface.tsx
  src/components/modules/chat/ui/components/ChatMessage.tsx
  src/components/modules/chat/ui/components/ConversationList.tsx
  src/components/modules/chat/ui/components/FileAttachment.tsx
  src/components/modules/chat/ui/components/FileUploadZone.tsx
  src/components/modules/chat/ui/pages/Chats.tsx
  src/components/modules/contact/hooks/tanstack/useUsersQuery.ts
  src/components/modules/escrow/hooks/multi-release/release-funds-milestone-dialog.hook.ts
  src/components/modules/escrow/hooks/single-release/release-funds-escrow-dialog.hook.ts
  src/components/modules/escrow/ui/cards/EscrowCard.tsx
  src/components/modules/escrow/ui/dialogs/cards/EntityCard.tsx
  src/components/modules/escrow/ui/filters/MyEscrowsFilter.tsx
  src/components/modules/report-issue/hooks/send-report-issue.hook.ts
  src/components/modules/report-issue/schema/report-issue.schema.ts
  src/components/modules/report-issue/server/report-issue.firebase.ts
  src/components/modules/report-issue/ui/forms/ReportIssueForm.tsx
  src/components/modules/report-issue/ui/pages/ReportIssueLogged.tsx
  src/components/modules/report-issue/ui/pages/ReportIssueNoLogged.tsx
  src/components/modules/setting/hooks/api-keys.hook.ts
  src/components/modules/setting/hooks/appearance-section.hook.ts
  src/components/modules/setting/hooks/settings.hook.ts
  src/components/modules/setting/server/api-key-firebase.ts
  src/components/modules/setting/services/request-api-key.service.ts
  src/components/modules/setting/ui/sections/APIKeys.tsx
  src/components/modules/setting/ui/utils/ProfileAvatar.tsx
  src/components/modules/users/hooks/public-profile.hook.ts
  src/core/store/data/@types/authentication.entity.ts
  src/core/store/data/index.ts
  src/core/store/data/slices/authentication.slice.ts
  yarn.lock
Labels: enhancement, core-dev
